echo Downloading GLoVe embedding file...
wget -P misc/ http://nlp.stanford.edu/data/glove.twitter.27B.zip
echo Extracting GLoVe embedding file...
7z e misc/glove.twitter.27B.zip -omisc
echo Downloading and extracting Sentiment140 dataset...
kaggle datasets download kazanova/sentiment140 -p data/ --unzip